[tool.pylint.'MESSAGES CONTROL']

disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-final-newline",
    "trailing-newlines",
    "trailing-whitespace",
    "logging-fstring-interpolation",
]
enable = [
    "logging-not-lazy",
]

[tool.pytest.ini_options]
pythonpath = [
  "src",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "prefect",
]