[tool.pylint.'MESSAGES CONTROL']

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "trailing-newlines",
    "trailing-whitespace",
]

[tool.pytest.ini_options]
pythonpath = [
  "src",
]